### ISSUE TITLE
Support for temporal methods for Column

### ISSUE THREAD

**Issue by amrit110** [data-apis/dataframe-api-compat#15]
Hi! Could there be support to perform temporal computations like (https://pola-rs.github.io/polars/py-polars/html/reference/series/temporal.html) on a column if its a datetime type?

So the use case would be something like this:

```python
def compute_years(df, col_name, new_col_name):
    df_std = df.__dataframe_consortium_standard__()
    dt_col = df_std.get_column_by_name(col_name)
    years_col = dt_col.dt.year() # not sure if this is the API we want, but something like that
    df_std = df_std.insert_column(years_col.rename(new_col_name))

    return df_std.dataframe
```

**Comment by MarcoGorelli** [comment]
yeah totally - could you add your request here please https://github.com/data-apis/dataframe-api/issues/260 ?

**Comment by MarcoGorelli** [comment]
also, we have a bi-weekly call about the design, if you have requests and/or would just like to listen, please do let me know and I can add you

**Comment by amrit110** [comment]
> yeah totally - could you add your request here please https://github.com/data-apis/dataframe-api/issues/260 ?

Yeah your description there seems to cover it! Yeah please do add me to the call. Would love to listen in, we are adopting the array and dataframe API standards in our project which has some processing functions for clinical ML pipelines as well as evaluation functions (https://github.com/VectorInstitute/cyclops).

**Comment by MarcoGorelli** [comment]
cool, I'll just need your email address - could you add me on LinkedIn https://www.linkedin.com/in/marcogorelli/ and then DM me it please?

the call will be at 17:00 UTC (28th  September)
